---
# configure routers with SNMP 
 
- name: configurtion SNMP
  ios_command:
    commands:
    - enable
    - configure terminal
    - snmp-server community GRCRocks rw
    - snmp-server community GRCRocks ro