---
- hosts: CSR1,CSR2
  gather_facts: false
  connection: local
  tasks:
  - name: show running config on router 
    ios_command:
      commands:
      - show running-config 
    register: config

  - name: save outbut backup to the back up folder
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "~/Cisco-Backup/{{inventory_hostname}}-config.txt"

#############################################################################################

  
  - name: IP route Configuration 
    ios_command:
      commands:
      - enable
      - configure terminal
      - ip route 0.0.0.0 0.0.0.0 gigabitEthernet 0/0/0
      - no shutdown 

##############################################################################################

  
  - name: Assinging console password  
    ios_command:
      commands:
      - enable
      - configure terminal
      - line console 0
      - password GRCCon
      - login 
##########################################################################################
  
  - name: Configure NTP server 
    ios_command:
      commands:
      - enable
      - configure terminal
      - ntp server 192.168.0.250

#################################################################################################
  
  - name: configurtion SNMP
    ios_command:
      commands:
      - enable
      - configure terminal
      - snmp-server community GRCRocks rw
      - snmp-server community GRCRocks ro
