---
- hosts: router CSR1
  gather_facts: false
  connection: local
  tasks:
  - name: show run 
    ios_command:
      commands:
      - en
      - conf t
      - banner motd "UNAUTHORIZED ACCESS PROHIBITED IT’S ONLY FOR IT385 STUDENT !"
      - do wr man
  - name: show run 
    ios_command:
      commands:
      - en
      - conf t
      - hostname ITrouter
      - do wr 
      