---
- hosts: router CSR1
  gather_facts: false
  connection: local
  tasks:
  - name: show run 
    ios_command:
      commands:
      - en
      - conf t
      - banner motd ~
      ############################################

           welcome to class
      ############################################ 
      ~
      - do wr man
