---
- hosts: CSR1
  gather_facts: false
  connection: local
  tasks:
  - name: show running config on router 
    ios_command:
      - show  running-config 
    rigister: config

  - name: save outbut backup to the back up folder
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "~/backup/{{inventory_hostname}}-config.txt"
