---
- host: localhost

  task:
  - name: Get Ansible date & time facts
    setup: 
      filter: "Ansible_date_time"
      gather_subset: "!all"

  - name: store Backup as fact
    set_fact:
      Backup: "{{ Ansible_date_time.date }}"

  - name: Create Directory {{hostvars.localhost.Backup}}
    file:
      path: 
      state: directory
  run_once: true

- host: CSR-Routers
  gather_facts: false

  tasks:
    - name: show run on the drvice
      ios_command:
        - show run
      register: config

- host: CSR-Routers
  gather_facts: false

  task:
    - name: save backup
      copy:
        content:"{{config.stdout[0]}}"
        dest: "./backup/{{ inventory_hostname }}-config.txt"
        

   
