---
- host: CSR1
  gather_facts: false

  tasks:
    - name: show run on the drvice
      ios_command:
        command:
        - show run
      register: config

- host: CSR-Routers
  gather_facts: false

  task:
    - name: save backup
      copy:
        content: "{{config.stdout[0]}}"
        dest: "./backup/{{ inventory_hostname }}-config.txt"
        

   
