---

- hosts: linux
  tasks:
  - name: create user (AJ/cisco1)
    user:
      name: "AJ Ahmadzai"
      password: "{{ 'cisco1' | password_hash('sha512') }}"
    become: yes

- hosts: db
  tasks:
  - name: Install mariadb
    become: yes
    apt:
      name: mariadb-server
      state: present

  - name: Enable MariaDB server
    become: yes
    service:
      name: mariadb
      enabled: yes

  - name: start Mariadb
    become: yes
    service:
      name: mariadb
      state: started

- hosts: web
  tasks:
  - name: install the apache
    become: yes
    apt:
      name: apache2 
      state: present
  - name: set apache to run
    become: yes
    service:
      name: apache2
      state: started
      enabled: yes
     
