---
- hosts: CSR2
  gather_facts: false
  connection: local
  tasks:  
  - name: Deploying OSPF Routing 
    ios_command:
      commands:
      - enable
      - configure terminal
      - router ospf 5
      - network 192.168.1.0 0.0.0.255 area 0
      - network 10.0.0.0 0.255.255.255 ara 0 
      - do wr 