---
- hosts: CSR2
  gather_facts: false
  connection: local
  tasks:  
  - name: No ip domain lookup  
    ios_command:
      commands:
      - en
      - conf t
      - enable password cisco
      - security passwords min-length 10
      - service password-encryption
      - line vty 0 15
      - exec-timeout 20 30
      - password cisco
      - login 
      - line vty 0 1