---

- hosts: linux
  tasks:
  - name: create user (AJ/cisco1)
    user:
      name: "mark"
      state: absent
    become: yes
    tags: remove

- hosts: db
  tasks:
  - name: Install mariadb
    become: yes
    tags: remove
    apt:
      name: mariadb-server
      state: absent


- hosts: web
  tasks:
  - name: install the apache
    become: yes
    tags: remove
    apt:
      name: apache2 
      state: absent

     
