---
- hosts: CSR2
  gather_facts: false
  connection: local
  tasks:  
  - name: No ip domain lookup  
    ios_command:
      commands:
      - en
      - conf t
      - no ip domain-lookup
      - do wr
########################################################################################
  - name: Deploying Banner Massage
    ios_command:
      commands:
      - enable
      - configure terminal
      - banner motd "UNAUTHORIZED ACCESS PROHIBITED IT’S ONLY FOR IT385 STUDENT !"
      - do wr
########################################################################################

  - name: Deploying hostname 
    ios_command:
      commands:
      - enable
      - configure terminal
      - hostname IT385Router
      - do wr 
#######################################################################################

  - name: Deploying Ip address to interface 
    ios_command:
      commands:
      - enable
      - configure terminal
      - hostname IT385Router
      - do wr 

#######################################################################################
- name: Deploying 
    ios_command:
      commands:
      - enable
      - configure terminal
      - interface gigabitEthernet3
      - ip address 192.168.0.1 255.255.255.0
      - no shutdown
