---
- hosts: CSR2
  gather_facts: false
  connection: local
  tasks:  
  - name: No ip domain lookup  
    ios_command:
      commands:
      - en
      - conf t
      - no ip domain-lookup
      - do wr
########################################################################################
  - name: Deploying Banner Massage
    ios_command:
      commands:
      - enable
      - configure terminal
      - banner motd "UNAUTHORIZED ACCESS PROHIBITED IT’S ONLY FOR IT385 STUDENT !"
      - do wr
########################################################################################

  - name: Deploying hostname 
    ios_command:
      commands:
      - enable
      - configure terminal
      - hostname IT385Router
      - do wr 
#######################################################################################

  - name: Deploying Ip address to interface 
    ios_command:
      commands:
      - enable
      - configure terminal
      - interface gigabitEthernet3
      - ip add 10.0.0.10 255.0.0.0
      - no sh
      
#####################################################################################

  - name: Deploying OSPF Routing 
    ios_command:
      commands:
      - enable
      - configure terminal
      - router ospf 5
      - network 192.168.1.0 0.0.0.255 area 0
      - network 10.0.0.0 0.255.255.255 ara 0 
      - do wr 

######################################################################################

  - name: assign password  
    ios_command:
      commands:
      - en
      - conf t
      - enable password cisco
      - security passwords min-length 10
      - service password-encryption
      - line vty 0 15
      - exec-timeout 20 30
      - password cisco
      - login 
      - line vty 0 1